### ISSUE TITLE
[win] On all OS versions the "Installation Complete" banner does not go away

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/installers#10]
The user has to quit the installer program by right click, popup, then quit. Perhaps the best thing is to have a "Close" button on the banner.

![selection_032](https://cloud.githubusercontent.com/assets/10051386/13827589/1f173d16-ebc6-11e5-9ffc-0e76a54ff39a.png)

**Comment by slavakimod** [comment]
Just click on the Pop-up window and it will smoothly disappear
