### ISSUE TITLE
[win] VM off after install and seeing various nasty errors when starting from VBox manager

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/installers#12]
This happens on all but Windows 7 and that's because the download of the management template never completed for me to get to this point. This screenshot is from Windows 10.

![selection_033](https://cloud.githubusercontent.com/assets/10051386/13827763/ec2ee092-ebc6-11e5-8730-5f87193378ca.png)

Some facts:
- After the installer completed, I saw the tray (had to manually launch) showed the VM as in the RUNNING state.
- I opened up the vbox manager and saw it was in the STOPPED state.
- When I tried to start I got these nasty messages
- When I tried to goto https://localhost:9999 there was a host refused connection message

This screenshot is from Windows 8:

![selection_035](https://cloud.githubusercontent.com/assets/10051386/13827957/d2e26e32-ebc7-11e5-8c27-4c36105adba0.png)

**Comment by slavakimod** [comment]
This happened because of opening Virtual Box console without administrative privileges. Replaced default shortcut with the one w/elevated privileges

**Comment by akarasulu** [comment]
This was fixed.
