### ISSUE TITLE
[Win] Installation fails if tray folder is not empty, need to inform user before

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#129]
If `<InstDir>\bin\tray` folder is not empty, installer can not unzip tray archive. Need to check before installation and inform user.  `<InstDir>\bin\tray` will not be deleted if any ssh session left opened.

**Comment by btemir** [comment]
With high probability  <InstDir>\bin\tray  folder is not empty (not cleaned on previous uninstall) if some of files are locked by applications - ssh sessions, directories opened etc. It should be closed by user only.

**Comment by btemir** [comment]
to check:
copy bin folder somewhere
uninstall Subutai
restore bin folder in Subutai installation directory
run SubutaiTray
run installer

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/21303776/09ed7b4e-c5eb-11e6-80c6-83cdd9857874.png)
Tested the ticket, result : 
After closing Tray, ssh sessions, and clicking OK it does start installation : 
![image](https://cloud.githubusercontent.com/assets/17665678/21303798/2cb1498a-c5eb-11e6-89ba-c27570543f72.png)
