### ISSUE TITLE
[Win] Installation fails on "Import snappy" stage if snappy files were not deleted

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#130]
If failed to delete snappy files on previous installation (MessageBox advising user to delete manually was shown) but user did not delete it, installation fails. 
![snappy](https://cloud.githubusercontent.com/assets/16958983/21250984/d8cf71c6-c373-11e6-9cd6-27c1a4666faf.PNG)

[VBoxSVC (1).log.txt](https://github.com/subutai-io/installers/files/656351/VBoxSVC.1.log.txt)

Need to delete files or show message

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/21300617/b2726f20-c5cf-11e6-95ff-2f7b384af2b5.png)
Tested the ticket, when Snappy VM was not removed a message ^^ appears.

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/21302447/10f1a15e-c5e1-11e6-84cb-f45f580f3a21.png)
![image](https://cloud.githubusercontent.com/assets/17665678/21302451/194da654-c5e1-11e6-9cb7-11124e92f8a9.png)
Deleted Snappy folder and installation started on Importing Snappy stage:
![image](https://cloud.githubusercontent.com/assets/17665678/21302472/5b2889ea-c5e1-11e6-9889-004ab67f447d.png)
