### ISSUE TITLE
[Win] Install/Uninstall does not work if installation directory name contains spaces

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#139]
need to add `"` to installation directory everywhere

**Comment by btemir** [comment]
![capture](https://cloud.githubusercontent.com/assets/16958983/21560809/9890f26c-ce8e-11e6-8754-881e2ad33dc5.PNG)

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/21564279/e4be2b92-ceb5-11e6-88c5-6d894c4ccfc5.png)
