### ISSUE TITLE
[Win] Change radio buttons to checkboxes for installation type

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#141]
Now we have 3 buttons:

- Full (RH+MH+Client)
- RH Only
- Client only 

Radio buttons allow to choose only one of them, that excludes installation of RH+Client

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/22008935/beffd57a-dca9-11e6-845f-733a4a03b2b1.png)
Got a testing installer from @btemir 
Tested Checkboxes: everything worked ok also tested full subutai installation and its features: 

1. Environment creation - success 
-from Hub and from SS 
2. Adding SSH key from Tray - success
   - Adding SSH key from SS - success
   - Adding SSH key from Hub - success
3. SSHing - from Tray - success
                       - from Hub -success
                       - from SS     - `fail` : 
`Oh, snap error code:4
Join to p2p swarm failed`  I think it was warming up and things 
4. Updating from Tray - success
5. Updating from SS - success

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/22009393/0b906852-dcad-11e6-8554-35e91e2d6277.png)
*Testing installation of RH only* 

Done installing RH only : 
1. Installation -success 
2. VM is running 
3. I can open RH from VirtualBox and execute some commands like : `sudo subutai info ipaddr`  `sudo subutai list -i,t,a` 
but mainly installation went well and no issues were encountered.

**Comment by btemir** [comment]
![fromslack](https://cloud.githubusercontent.com/assets/16958983/22013960/bc153a96-dcc5-11e6-82f9-951f2f427f41.PNG)
