### ISSUE TITLE
[win] Make tray application launched on each startup of machine where it is installed

### ISSUE THREAD

**Issue by anuriddinov** [subutai-io/installers#15]

**Comment by btemir** [comment]
http://www.howtogeek.com/228467/how-to-make-a-program-run-at-startup-on-any-computer/
On Windows 7 and earlier versions of Windows, the Start menu contained a “Startup” folder to make this easy. On these versions of Windows, you can simply open your Start menu, locate a shortcut to an application you want to start automatically, right-click it, and select Copy. Next, locate the Startup folder under All Apps in the Start menu, right-click it, and select Paste to paste a copy of that shortcut.

This is done on install (have Subutai shortcuts in all folders needed) but application does not start.

**Comment by btemir** [comment]
Changed in Registry 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

**Comment by akylbekesenaliev** [comment]
![image](https://cloud.githubusercontent.com/assets/17665678/21301917/eb71cb98-c5db-11e6-8b53-e1ec8461c527.png)
Tested the ticket, testing result : Success 
That Timeout  - this is because of my wifi not being connected at the time.
