### ISSUE TITLE
Windows installers assigning too many processors to snappy RH VM.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/installers#17]
This is an important and immediately concern because it cripples peoples machines.

A friend installed subutai last night and it totally killed his laptop. He's running Windows 7 and it took 8 processors for the virtual machine. I do not think the windows installer is properly allocating the processors to the VM it uses. If 8 it should perhaps assign 2 or maybe 4 maximum. The core/processor calculation and settings should be handled correctly.

**Comment by btemir** [comment]
Setting of number of processor added, minimal is 2 processor/cores.
