### ISSUE TITLE
Code signing of the windows installer

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/installers#22]

**Comment by btemir** [comment]
Created test certificate and signed code. Need real certificate.

**Comment by btemir** [comment]
Signed installer components (Deployment.exe, vs_preinstall.exe, uninstall-clean.exe) and SubutaiTray.exe.

**Comment by btemir** [comment]
Code signing to sign 1.exe file:
signtool sign /a /f  <Sertificate.pfx> /p <password> /t http://timestamp.comodoca.com/authenticode <1.exe>
