### ISSUE TITLE
Fix warning on windows when ssh invoked about now user .ssh directory

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/installers#23]

**Comment by btemir** [comment]
tried to fix with defining %HOME% environment variable (as described), but it does not help, need to research more.

**Comment by btemir** [comment]
Changed to OpenSSH (http://www.mls-software.com/opensshd.html), created shortcut to <%HOMEDRIVE%>Users\ in parent directory for ssh bin directory (in our case in Subutai).
