### ISSUE TITLE
[win] uninstall was removed from the windows installer

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/installers#25]
The uninstall must be added back immediately.

**Comment by btemir** [comment]
changed script so it checks if environment variable %SUBUTAI% exists and removes folders and files only after that. Now script needs user attention (to eliminate "virus" alerts). Need to change to code

**Comment by btemir** [comment]
need to make removing of files and folder "silent", without prompting user.

**Comment by btemir** [comment]
Wrote application for uninstall-clean. Stopping p2p service, tray app and deleting files. Need to clean register from Tray and P2P settings.
