### ISSUE TITLE
[Initialization of SS frame] Should change fonts and color.

### ISSUE THREAD

**Issue by postoronnii** [subutai-io/installers#29]
Now we have 3 different fonts here, should change it to one font and change purple color to blue.
![screenshot_1](https://cloud.githubusercontent.com/assets/11311924/15428236/f7bfbb34-1ebb-11e6-9b21-f55ff680af1e.png)

**Comment by btemir** [comment]
will be changed after DevExpress eliminated if needed (as we are transferring to launcher)
