### ISSUE TITLE
Can't observe on Hub side created on SS side enironments and can't observe on SS side created on Hub environments.

### ISSUE THREAD

**Issue by postoronnii** [subutai-io/installers#32]
For replay this bug you need:

Test case
1) Go to SS and create envi.
2) Go to Hub and create envi.

Result: you can't observe on Hub side created on SS side environments and can't observe on SS side created on Hub environments.
![env](https://cloud.githubusercontent.com/assets/11311924/15640478/33d34e2e-265a-11e6-887c-cd762accb46d.jpg)
![env2](https://cloud.githubusercontent.com/assets/11311924/15640479/398e8522-265a-11e6-819a-2df3bb91fd52.jpg)

**Comment by zubaidullo** [comment]
When peer sending Environment data to Hub, fingerprint from context is different from normal heartbeat fingerprint. That's why Hub can't find peer from db

**Comment by zubaidullo** [comment]
Ex: same peer sending
fingerprints: 
818E913A6C3D291A21C7865D0B98F50B80F72ED1
8120aba66000a01bd8e3020f202bc7d1835422f6

**Comment by dilshat** [comment]
Fixed by https://github.com/subutai-io/base/pull/960
