### ISSUE TITLE
Add an option to start SS by default after restart the system.

### ISSUE THREAD

**Issue by postoronnii** [subutai-io/installers#33]
After restart the system, to start to work with SS the user has to run VM at first.  
The best way: add an option to start SS by default every time when you restart the system, like µTorrent does. For that during the installation process, we have to ask user about it :
![torrent setup](https://cloud.githubusercontent.com/assets/11311924/15662703/3364b8b8-2715-11e6-940a-6c35262f7b7f.jpg)

**Comment by btemir** [comment]
User can start-stop-remove VM from tray. What if user does not want VM running  immediately after reboot. May be we need to run VM when tray starts.

**Comment by NikolaiB** [comment]
@btemir for that we will have an additional settings, to let the user option to choose.

![torrent setup](https://cloud.githubusercontent.com/assets/11311924/15665212/6da084ba-272b-11e6-9a85-f3314a1e5c3d.jpg)
