### ISSUE TITLE
Can't run SS if I chosen an option to install to another directory.

### ISSUE THREAD

**Issue by NickolaiVarin** [subutai-io/installers#35]
![afterinstall](https://cloud.githubusercontent.com/assets/16968797/15665296/a37e2766-2723-11e6-9c8e-c0e1644f6969.jpg)

For reproduce this bug you need:

Test case
Preparation step: Install SS with old installer on Windows OS machine.
1. Download from SS site DevSS installer.
2. Start to install.
3. Observe message: "Do yo want upgrade old SS or install it on another directory"
4. Chose install to another derectory.
5. Cleck on next button until instalation will be done.

Result: 
When try to launch trough SS tray, observe: "This site can't be reached" page. Also, observe error at the bottom: Refresh containers info error: NOT_JSON_DOC_ERROR.

**Comment by Lezh1k** [comment]
That's because of previous installations. Tray stores settings in Windows registry, so maybe we need to remove that setting from registry and use hardcoded path or path based on %Subutai% path variable.

**Comment by btemir** [comment]
There is also problem with SS P2P service - it attempts to run from old path. Need to clean register from some tray and p2p keys.

**Comment by btemir** [comment]
Before new installation, if You are going to install to another directory, please be sure that windows service "Subutai Social P2P" does not exist. If exist, run following command as administrator in Command Line Interface:
nssm remove "Subutai Social P2P"

**Comment by btemir** [comment]
After installation in another directory with previous version of installer uninstall can hang and will not finish. After that Registry should be cleaned properly.

**Comment by NickolaiVarin** [comment]
Not actual.
