### ISSUE TITLE
[Mac OS] Installation failed

### ISSUE THREAD

**Issue by ernistkg** [subutai-io/installers#36]
Installing from scratch...

link to installer:
http://cdn.subut.ai:8080/kurjun/rest/raw/download?name=subutai-network-installer.pkg

![screen shot 2016-06-03 at 6 32 15 pm](https://cloud.githubusercontent.com/assets/13309012/15778684/90a91d7e-29b9-11e6-9250-cfb282b286af.png)
![image](https://cloud.githubusercontent.com/assets/13309012/15778721/c9eb1b82-29b9-11e6-90c6-be5588b4aa88.png)
![image](https://cloud.githubusercontent.com/assets/13309012/15778746/f31c044e-29b9-11e6-842c-8cc1208d105c.png)

[install.log.txt](https://github.com/subutai-io/installers/files/297566/install.log.txt)
[p2p.log.txt](https://github.com/subutai-io/installers/files/297577/p2p.log.txt)

**Comment by p1gmale0n** [comment]
```
         30.64 MB / 121.08 MB   25.31% 3m50stime="2016-06-03 12:10:26" level=fatal msg="Writing file management-subutai-template_4.0.0_amd64.tar.gz, u
nexpected EOF"
```

cannot download template

**Comment by ernistkg** [comment]
Trying to install "Net Installer Dev"
![image](https://cloud.githubusercontent.com/assets/13309012/15779969/2cd5cf92-29c1-11e6-80bb-acc21ace32a3.png)

[install.log.txt](https://github.com/subutai-io/installers/files/297642/install.log.txt)

**Comment by ernistkg** [comment]
For Master Installer
[install.log.txt](https://github.com/subutai-io/installers/files/297694/install.log.txt)

**Comment by asanaliev** [comment]
Installation on my Mac failed too. 
[install.log.txt](https://github.com/subutai-io/installers/files/300450/install.log.txt)

**Comment by asanaliev** [comment]
Comments from @Ernisto 
`Installing through Ethernet helped me. I don't know why.
Before there was no problem installing through Wi-Fi.`

`61.37 MB / 67.15 MB   91.40% 5stime="2016-06-06 12:18:35" level=fatal msg="Writing file master-subutai-template_4.0.0_amd64.tar.gz, read tcp 192.168.0.107:51689->109.201.160.217:8338: read: connection timed out" 
Jun  6 18:18:55 tulpar-2 installd[35997]: ./postinstall: time="2016-06-06 12:18:55" level=info msg="[Importing management]"`
same issue

**Comment by p1gmale0n** [comment]
can we close this?

**Comment by asanaliev** [comment]
I could successfully installed dev version of Mac/Net Installer.

**Comment by asanaliev** [comment]
Yesterday I removed VirtualBox from my Mac, started installing the dev version of installer (downloaded latest from the site). I left option by default. 

![image](https://cloud.githubusercontent.com/assets/7465404/15983914/2221ec16-2fd9-11e6-9309-70a91ce16652.png)

Installation take too long so I killed it (Force Quit in Activity Monitor). Now I am getting this message every time as I start the installer. 

![image](https://cloud.githubusercontent.com/assets/7465404/15983892/2c03cc32-2fd8-11e6-900b-2d46096d1eed.png)

It stays on this step without any changes.

[install.log.txt](https://github.com/subutai-io/installers/files/310154/install.log.txt)

**Comment by p1gmale0n** [comment]
`VBoxManage: error: VD: error VERR_NO_MEMORY opening image file 'snappy-disk1.vmdk' (VERR_NO_MEMORY)`
need to restart os

**Comment by asanaliev** [comment]
**Note: this is before restarting OS.**

I killed the process `installd` in Activity Monitor and restarted the installation. Got some progress but installation failed anyway. 

![image](https://cloud.githubusercontent.com/assets/7465404/15984467/0c728a3c-2fee-11e6-839b-f76cb5afd1de.png)

But I see the tray and VirtualBox were installed. 

![image](https://cloud.githubusercontent.com/assets/7465404/15984479/7f1c9b86-2fee-11e6-9fe9-f43de657d1bd.png)

![image](https://cloud.githubusercontent.com/assets/7465404/15984482/8a56164e-2fee-11e6-970f-3bc6e672c2e8.png)

[install.log.txt](https://github.com/subutai-io/installers/files/310178/install.log.txt)

**Comment by asanaliev** [comment]
I tried again 3 times. Unfortunately, all attempts finished with fails. On two of installations there was the message "Installation in progress" without any change.

The last installation showed success message but VirtualBox wasn't installed and I can not see the tray icon when launch /Applications/Subutai/SubutaiTray (no process in Activity Monitor for "subutai"). Restarting my laptop doesn't help.

[install.log.txt](https://github.com/subutai-io/installers/files/310435/install.log.txt)

**Comment by p1gmale0n** [comment]
on 1st attempt, you cannot download template:

```
         64.91 MB / 215.98 MB   30.05% 2m30stime="2016-06-11 08:46:29" level=fatal msg="Writing file management-subutai-template_4.0.0-dev_amd64.tar.g
z, read tcp 192.168.0.112:35980->158.181.200.73:8338: read: connection timed out"
```

then 2nd attempt:

```
         99.77 MB / 215.98 MB   46.19% 54stime="2016-06-11 18:59:38" level=fatal msg="Writing file management-subutai-template_4.0.0-dev_amd64.tar.gz,
 read tcp 192.168.0.118:37836->158.181.200.73:8338: read: no route to host"
```

3rd attempt:

```
Jun 12 01:06:53 tulpar-2 installd[408]: ./postinstall: time="2016-06-11 19:06:53" level=info msg="[Downloading management]"
Jun 12 01:10:17 tulpar-2 installd[408]: PackageKit: Removing client PKInstallDaemonClient pid=488, uid=501 (/System/Library/CoreServices/Installer.app
/Contents/MacOS/Installer)
Jun 12 01:10:21 tulpar-2 install_monitor[491]: Caught installd exit
```

installation stopeed before download ends
and 4th attempt:

```
Jun 12 01:16:02 tulpar-2 installd[1100]: ./postinstall: time="2016-06-11 19:16:02" level=info msg="[Subutai Management UI will shortly be available at
 https://192.168.0.119:8443 (admin/secret)]"
Jun 12 01:16:02 tulpar-2 installd[1100]: ./postinstall: time="2016-06-11 19:16:02" level=info msg="[SSH access to Management: ssh root@192.168.0.119 -
p2222 (ubuntu)]"
Jun 12 01:16:02 tulpar-2 installd[1100]: ./postinstall: time="2016-06-11 19:16:02" level=info msg="[Don't forget to change default passwords]"
```

installed

**Comment by dilshat** [comment]
why  this happens ? is this related to Gorjun or network problem @p1gmale0n

**Comment by p1gmale0n** [comment]
> is this related to Gorjun or network problem
> cannot identify - network or Gorjun, but one of them

I would put on network problems.

**Comment by asanaliev** [comment]
@p1gmale0n seems we have to give some message about these issues. Otherwise, it is unclear why installation failed.

**Comment by p1gmale0n** [comment]
@asanaliev unfortunately, current installer not have any methods for feedback to user

**Comment by asanaliev** [comment]
I tested the installation 5 times. Could install once only without any issues:
1. Lost connection
2. Success
3. Lost connection 
4. Lost connection
5. Lost connection

# 

**Install 1**

Till this moment everything was smooth:

```
Jun 14 00:30:31 tulpar-2 installd[405]: ./postinstall: time="2016-06-13 18:30:31" level=info msg="[Downloading management]"
```

After some time I lost network connection:

```
64 bytes from 8.8.8.8: icmp_seq=369 ttl=53 time=1076.928 ms
64 bytes from 8.8.8.8: icmp_seq=370 ttl=53 time=75.485 ms
64 bytes from 8.8.8.8: icmp_seq=371 ttl=53 time=269.577 ms
Request timeout for icmp_seq 374
Request timeout for icmp_seq 375
Request timeout for icmp_seq 376
```

Strange thing is that I don't have connection but wifi icon shows connection is active (this is true for all 4 cases when I lost connection):

![image](https://cloud.githubusercontent.com/assets/7465404/16022820/8f3de328-31db-11e6-871e-bc85d1b77944.png)

I had to turn off/on wifi and the installation completed successfully. 

```
Request timeout for icmp_seq 434
Request timeout for icmp_seq 435
Request timeout for icmp_seq 436
ping: sendto: Network is down
Request timeout for icmp_seq 437
ping: sendto: No route to host
Request timeout for icmp_seq 438
ping: sendto: No route to host
Request timeout for icmp_seq 439
ping: sendto: No route to host
Request timeout for icmp_seq 440
ping: sendto: No route to host
Request timeout for icmp_seq 441
ping: sendto: No route to host
Request timeout for icmp_seq 442
Request timeout for icmp_seq 443
64 bytes from 8.8.8.8: icmp_seq=444 ttl=53 time=75.033 ms
64 bytes from 8.8.8.8: icmp_seq=445 ttl=53 time=181.780 ms
64 bytes from 8.8.8.8: icmp_seq=446 ttl=53 time=182.912 ms
```

[install-1.log.txt](https://github.com/subutai-io/installers/files/312693/install-1.log.txt)
[ping-1.txt](https://github.com/subutai-io/installers/files/312694/ping-1.txt)

# 

**Install 2**
Installed without any issues. 
[install-2.log.txt](https://github.com/subutai-io/installers/files/312695/install-2.log.txt)
[ping-2.txt](https://github.com/subutai-io/installers/files/312696/ping-2.txt)

# 

**Install 3**

Again lost connection here:

```
Jun 14 00:58:17 tulpar-2 installd[6883]: ./postinstall: time="2016-06-13 18:58:17" level=info msg="[Downloading openjre8]" 
```

```
64 bytes from 8.8.8.8: icmp_seq=1585 ttl=53 time=77.209 ms
64 bytes from 8.8.8.8: icmp_seq=1586 ttl=53 time=601.933 ms
64 bytes from 8.8.8.8: icmp_seq=1587 ttl=53 time=1013.008 ms
Request timeout for icmp_seq 1589
Request timeout for icmp_seq 1590
Request timeout for icmp_seq 1591
```

Installation finished with failure. Restarted laptop.
[install-3.log.txt](https://github.com/subutai-io/installers/files/312707/install-3.log.txt)
[ping-3.txt](https://github.com/subutai-io/installers/files/312709/ping-3.txt)

# 

**Install 4**
Lost connection here:

```
Jun 14 01:53:37 tulpar-2 installd[406]: ./postinstall: time="2016-06-13 19:53:37" level=info msg="[Downloading management]"
```

```
64 bytes from 8.8.8.8: icmp_seq=267 ttl=53 time=77.404 ms
64 bytes from 8.8.8.8: icmp_seq=268 ttl=53 time=76.697 ms
64 bytes from 8.8.8.8: icmp_seq=269 ttl=53 time=73.789 ms
Request timeout for icmp_seq 270
Request timeout for icmp_seq 271
Request timeout for icmp_seq 272
```

Reset wifi manually:

```
ping: sendto: No route to host
Request timeout for icmp_seq 344
ping: sendto: No route to host
Request timeout for icmp_seq 345
Request timeout for icmp_seq 346
64 bytes from 8.8.8.8: icmp_seq=347 ttl=53 time=75.540 ms
64 bytes from 8.8.8.8: icmp_seq=348 ttl=53 time=76.000 ms
64 bytes from 8.8.8.8: icmp_seq=349 ttl=53 time=74.275 ms
```

Install completed successfully. 
[install-4.log.txt](https://github.com/subutai-io/installers/files/312712/install-4.log.txt)
[ping-4.txt](https://github.com/subutai-io/installers/files/312713/ping-4.txt)

# 

**Install 5**
Same as Install 4.
[install-5.log.txt](https://github.com/subutai-io/installers/files/312718/install-5.log.txt)
[ping-5.txt](https://github.com/subutai-io/installers/files/312719/ping-5.txt)

# 

**Download Test**
To verify that I don't have any issues with usual connection or network interface, I tested download with curl and wget. I downloaded 5 times AppScale template (~1 GB) from Gorjun. Each time I could download successfully (checked md5 always) and didn't lose connection.
[download-test.txt](https://github.com/subutai-io/installers/files/312732/download-test.txt)
[download-ping.txt](https://github.com/subutai-io/installers/files/312733/download-ping.txt)

**Comment by asanaliev** [comment]
I found that installation fails if we select MH when using WiFi connection.

Using WiFi connection:
- Failed if MH is selected 
- Successfully installed without MH

Using Ethernet cable:
- Successfully installed with and without MH

(I tested each of above cases at least 5 times.)

Seems something happens with network settings (or adapters) in VirtualBox or MacOS when importing management/master/openjre. As a result I lose wifi connection and have to turn it on manually (otherwise it doesn't get back automatically).

Note also, when I lose wifi when installing if I turn wifi on the installation completes successfully.

**Comment by asanaliev** [comment]
Made the following test cases. 
1. If the install completes successfully, stop and start of subutai VM (with management imported) doesn't give any issues with wifi. (Tested 5 times.)
2. Installed once and reimported management (destroy/import, 5 times). Also didn't get any wifi issues.
3. Installed without MH (5 times), then import management. Success always. 
4. Installed with MH (~7-10 times). About 80% completes with loosing wifi connection and as a result install failure. I notices that this issues happens mostly when downloading master/management/openjre, or sometimes as install completes.

**Comment by asanaliev** [comment]
I found this in /var/log/system.log:

```
grep -i 'warning.*SubutaiTray' /var/log/system.log
Jun 16 01:55:58 tulpar-2 airportd[65]: WARNING: SubutaiTray (973) is not entitled for com.apple.wifi.scan, temporarily allowing request with background priority —— all entitlement requirements will be strictly enforced in a future release
Jun 16 02:52:30 tulpar-2 airportd[65]: WARNING: SubutaiTray (1032) is not entitled for com.apple.wifi.scan, temporarily allowing request with background priority —— all entitlement requirements will be strictly enforced in a future release
```

Also getting this with each install:

```
Jun 16 02:53:27 tulpar-2 kernel[0]: process SubutaiTray[1032] caught causing excessive wakeups. Observed wakeups rate (per sec): 791; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45414
Jun 16 02:53:27 tulpar-2 com.apple.xpc.launchd[1] (com.apple.ReportCrash[1113]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
Jun 16 02:53:27 tulpar-2 ReportCrash[1113]: Invoking spindump for pid=1032 wakeups_rate=791 duration=57 because of excessive wakeups
Jun 16 02:53:31 tulpar-2 spindump[619]: Saved wakeups_resource.diag report for SubutaiTray version ??? (???) to /Library/Logs/DiagnosticReports/SubutaiTray_2016-06-16-025331_tulpar-2.wakeups_resource.diag
```

Although some installs (~20%) complete successfully.

[SubutaiTray_2016-06-16-032048_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317336/SubutaiTray_2016-06-16-032048_tulpar-2.wakeups_resource.diag.txt)
[SubutaiTray_2016-06-16-035842_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317337/SubutaiTray_2016-06-16-035842_tulpar-2.wakeups_resource.diag.txt)
[SubutaiTray_2016-06-16-041045_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317338/SubutaiTray_2016-06-16-041045_tulpar-2.wakeups_resource.diag.txt)
[SubutaiTray_2016-06-16-042856_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317339/SubutaiTray_2016-06-16-042856_tulpar-2.wakeups_resource.diag.txt)
[VBoxHeadless_2016-06-16-032401_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317341/VBoxHeadless_2016-06-16-032401_tulpar-2.wakeups_resource.diag.txt)
[VBoxHeadless_2016-06-16-041418_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317340/VBoxHeadless_2016-06-16-041418_tulpar-2.wakeups_resource.diag.txt)
[VBoxHeadless_2016-06-16-043218_tulpar-2.wakeups_resource.diag.txt](https://github.com/subutai-io/installers/files/317342/VBoxHeadless_2016-06-16-043218_tulpar-2.wakeups_resource.diag.txt)

**Comment by p1gmale0n** [comment]
@asanaliev interesting.. 
tray.app searching of local peer can have side effect
i will build, for you, installer without launching tray.app

**Comment by asanaliev** [comment]
Shahri could also install without errors.
