### ISSUE TITLE
[Win] [VM] Can't start VM after reboot the system.

### ISSUE THREAD

**Issue by postoronnii** [subutai-io/installers#37]
For replay this bug you need:

Test case
1) Install SS through installer, run it. Then reboot the system (you can save the state or not).
2) After reboot, run VM. 

Result: you can observe that VM shows an error.
![virtualbox - error](https://cloud.githubusercontent.com/assets/11311924/15803293/317b8108-2af8-11e6-9bb7-a9291d47db7e.jpg)

**Comment by btemir** [comment]
Oracle VirtualBox need to be reinstalled. On reinstall Repair option can be chosen.

**Comment by tzununbekov** [comment]
Faced the same issue. Oracle VirtualBox removing/reinstallation/repair is not working:

![vbdelerr](https://cloud.githubusercontent.com/assets/13515865/15918745/fb41edb6-2e2b-11e6-8d26-727f4953e255.png)
![vbdelerr2](https://cloud.githubusercontent.com/assets/13515865/15918744/fb4101c6-2e2b-11e6-8f9d-a69486df0929.png)

**Comment by btemir** [comment]
The cause of this is VBox installed on top of previous installation. Fixed by checking if VBox already installed. If so, will not install.

**Comment by postoronnii** [comment]
can not reproduce.
