### ISSUE TITLE
[Win] Install TAP utilities during TUN/TAP driver installation

### ISSUE THREAD

**Issue by crioto** [subutai-io/installers#39]
Utilities from TUN/TAP driver should be installed along with the driver and directory with *.bat scripts should persist in %PATH%

**Comment by btemir** [comment]
On Win 7 TAP-Windows\bin was not added to user's Path (fixed). On Win10 and Win8-8.1 Path was modified. TAP interface gets proper IP address. On win-vmware-win configuration there is ping and ssh, on lin-vmware-win - no ping.
