### ISSUE TITLE
Remove "Always on top" property from windows installer

### ISSUE THREAD

**Issue by soffokl** [subutai-io/installers#41]
Subutai installation window should not be always on top of other windows, it's very annoying. 
No companies use such properties for their installer, and we should not too. 
![image](https://cloud.githubusercontent.com/assets/8612618/15853947/243f1a40-2cc9-11e6-88a4-44293f33a39c.png)

**Comment by btemir** [comment]
Can not remove this property as installers needs user attention (and can not add Minimize button right now. If user doesn't want to see that window he can click on Subutai icon in task bar:
![taskbaricon](https://cloud.githubusercontent.com/assets/16958983/15858983/fca25aa2-2c77-11e6-985e-43fe3fb7043a.PNG)
or just move from center of the screen

Another option: design of this form will be changed, and minimize button cam be placed on form to minimize window if needed

**Comment by soffokl** [comment]
> installers needs user attention

@btemir Why all other installer live without it? 
Attention should not be mandatory. 
Minimizing by clicking on app on taskbar is not evident. I'm always use just Alt+Tab to switching windows. 
Why we need to restrict it. I do not see any reasons for that.

**Comment by btemir** [comment]
Installer needs user's attention as in some (TAP driver installation, firewall configuration) cases dialog windows can be produced and if installer's window will not be on top, user can never see it. GUI will be changed anyways, and probably this problem gone.

**Comment by btemir** [comment]
removed
