### ISSUE TITLE
[Linux, Deb] Can not run Tray after installation from debian

### ISSUE THREAD

**Issue by dilshat** [subutai-io/installers#42]
I purged previous installation of p2p and tray and then installed last p2p and tray debs.
When trying to run tray it gives the following error:

`dilshat@sol:~/Downloads$ subutai-tray 
This application failed to start because it could not find or load the Qt platform plugin "xcb".
Reinstalling the application may fix this problem.
Aborted (core dumped)`

Then I tried to install Qt platform `sudo apt-get install qt5-default` but it didnt help

OS: Ubuntu 16.04 LTS

**Comment by Lezh1k** [comment]
Can't reproduce on clear machine. Maybe that's because ubuntu 15.10 was updated to 16.04.

**Comment by dilshat** [comment]
Fixed with last deb

**Comment by akarasulu** [comment]
@Dilshat  👍  can you update the status page?
