### ISSUE TITLE
[Win 7] Installation failed with wrong message about requirements

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/installers#47]
Today (~16pm KGT) I downloaded dev version of Windows installer from subutai.io. But installation failed. 

I am not sure if this is error message or just reminding a user. But it gives an impression that I don't have Internet connection, although I have (could ping successfully Hub). 

![image](https://cloud.githubusercontent.com/assets/7465404/15984864/e671e400-2ffb-11e6-81d9-5db67eb1d8a0.png)

Installation failed with this message:

![image](https://cloud.githubusercontent.com/assets/7465404/15984890/7de4b3c6-2ffc-11e6-8585-1ecea2767871.png)

But seems my PC config meets those requirements.

![image](https://cloud.githubusercontent.com/assets/7465404/15984897/9fc226fe-2ffc-11e6-9b50-eaa68dd3afc9.png)

Also, I can find any logs in C:/Subutai/bin.

**Comment by btemir** [comment]
First aid - to run IExplorer and lower security level.

**Comment by btemir** [comment]
Can not reproduce this error on fresh system. On user's system: stopped Windows firewall and windows defender services - but it did not help. After that run Internet Explorer (it used to define if Internet connection present and lowered security level) - and Installer started to work. Need some research. Need to check if windows firewall and windows defender services should actually be stopped.

**Comment by btemir** [comment]
Situation was reproduced when network adapter connected to Internet was disabled in time of download. Installation was finished, adapter enabled, ping worked. But installer showed "No Internet connection". Started to work after refresh page (any) in Internet Explorer (simply first action in Internet Explorer?)

**Comment by btemir** [comment]
It seems to reload any page in Internet Explorer it's enough
