### ISSUE TITLE
[Win 8] Installation freezes on 'Waiting for SSH' step 

### ISSUE THREAD

**Issue by ezununbekov** [subutai-io/installers#49]
![unnamed](https://cloud.githubusercontent.com/assets/16970241/16027904/f5b801d6-31fb-11e6-81d0-27bb6f2dcaec.jpg)

However, after closing this window in about 10 minutes, Subutai seems to be installed and can be launched

![image](https://cloud.githubusercontent.com/assets/16970241/16028012/cbee2be0-31fc-11e6-8f40-d8e56f1968ed.png)

Here is log
[2016-06-14_install_log.txt](https://github.com/subutai-io/installers/files/312955/2016-06-14_install_log.txt)

**Comment by ezununbekov** [comment]
After uninstall and install again on 'Waiting for SSH' step connection got limited

![unnamed 2](https://cloud.githubusercontent.com/assets/16970241/16029021/2fa87b9a-3207-11e6-8a4c-056c489df528.jpg)

[2016-06-14_install_log (2).txt](https://github.com/subutai-io/installers/files/313007/2016-06-14_install_log.2.txt)

**Comment by btemir** [comment]
Cause of this situation -  network interfaces for Virtual machine were not configured properly, so VM is not accessible

**Comment by ezununbekov** [comment]
Still cannot install properly

![1](https://cloud.githubusercontent.com/assets/16970241/16077918/81a3c3fc-331d-11e6-9d6c-db85203e4875.JPG)
- this happens during installation. After clicking OK, installation continues and freezes again on Waiting for SSH step. Internet connection gets limited too, as before.

Logs 
[2016-06-15_install_log.txt](https://github.com/subutai-io/installers/files/316024/2016-06-15_install_log.txt)

**Comment by btemir** [comment]
Improper VBox Host-Only Interface adapter settings.

https://www.virtualbox.org/ticket/8796
https://forums.virtualbox.org/viewtopic.php?p=319146&sid=3180e15042fe1eab9fcad61a4df9e866#p319146
http://www.ihaveapc.com/2013/06/how-to-fix-error-message-in-order-to-configure-tcpip-you-must-install-and-enable-network-adapter-error-in-windows/
http://superuser.com/questions/873189/cant-set-manual-ip-to-virtualbox-host-only-adapter-in-centos-6-5

**Comment by akarasulu** [comment]
@tzununbekov @soffokl can you guys check this out to offload @btemir ?

**Comment by soffokl** [comment]
@akarasulu already asked about it yesterday. There are two possible reasons: 
1) Wrong host configuration. In this case I need access to this machine to check.
2) It could be bug in VirtualBox. We need to find workaround in this case. 

@btemir Do you using only "host-only" adapter to connect to the RH? If it's not accessible we can use forwarded port on NAT interface as reserve connection?

**Comment by btemir** [comment]
@soffokl: yes, I use. I had situations like this when I have no host-only adapter with address 192.186.56.1 on machine and need to create new (problem is adapter's name on Windows), now fixed (but I can configure adapters with static address), but yes, I need to think how to use nat in this case, when adapter is unconfigurable.

**Comment by ezununbekov** [comment]
Installed successfully
