### ISSUE TITLE
[Linux, Deb] Cannot start SubutaiTray

### ISSUE THREAD

**Issue by ezununbekov** [subutai-io/installers#52]
I installed subutai-p2p and subutai-tray. Starting subutai-tray gives this:

![subutai-tray](https://cloud.githubusercontent.com/assets/16970241/16116237/826323b6-33ed-11e6-8bd2-f06e054bcc83.jpg)

**Comment by akarasulu** [comment]
This should be easy to fix. @Lezh1k is this due to something being missing in deb package?

**Comment by Lezh1k** [comment]
Changed build to static. Fixed.
