### ISSUE TITLE
[Win] Oh snap container is not ready (invalid state)

### ISSUE THREAD

**Issue by larenso** [subutai-io/installers#53]
1) Install fresh Subutai
2) create environment 1 container
3) try to ssh to container (you will see shell trying to connect with timeout) - as expected
4) generate ssh-key in tray
5) try to ssh to container (you will see error oh snap) - seem like the state of container is saved somewhere

I had to restart the tray in order to run ssh container again

**Comment by larenso** [comment]
also found that during connection in the console the following:
Could not create directory /home/2ch/.ssh
Connection closed 10.28.234.1

**Comment by btemir** [comment]
usually "Could not create directory /home/2ch/.ssh" allows to connect with ssh, it's not an error
Please, this bug is not related to installer, its tray/hub/p2p issue

**Comment by larenso** [comment]
Digging into a problem, we found that it occurs, because we cannot ping resource host in windows, windows and p2p related problem.
https://github.com/subutai-io/p2p/issues/152
