### ISSUE TITLE
[Mac] VBox get VERR_NO_MEMORY on ova importing

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/installers#54]
Mac OS: El Captain 10.11
VirtualBox: 5.0.20 
Installer: Latest one uploaded today by @p1gmale0n (md5: 763609d989b12e037ced60034702f61f)
# 

I could reproduce this issue three times. Each time I had VirtualBox running, without any VMs. 

![image](https://cloud.githubusercontent.com/assets/7465404/16128090/0cc88252-3421-11e6-97df-dbe166bbef7e.png)

The installer comes to state "running package scripts" and stays there without any progress. But I can successfully do installation if VirtualBox is not running or not installed. 

These are install.log for three cases when I failed:
[vbox-preinstalled-error.txt](https://github.com/subutai-io/installers/files/319065/vbox-preinstalled-error.txt)
[vbox-preinstalled-error-2.txt](https://github.com/subutai-io/installers/files/319064/vbox-preinstalled-error-2.txt)
[vbox-preinstalled-error-3.txt](https://github.com/subutai-io/installers/files/319066/vbox-preinstalled-error-3.txt)

**Comment by p1gmale0n** [comment]
@asanaliev this issue related to VBox. on log file you can see:

```
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: Interpreting /Applications/Subutai/snappy.ova...
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: OK.
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: 0%...
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: Progress state: VBOX_E_FILE_ERROR
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: VBoxManage: error: Appliance import failed
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: VBoxManage: error: Could not open the medium storage unit 'snappy-disk1.vmdk'.
Jun 16 22:18:08 tulpar-2 installd[17059]: ./postinstall: VBoxManage: error: VD: error VERR_NO_MEMORY opening image file 'snappy-disk1.vmdk' (VERR_NO_M
EMORY)
```

thats mean:
ova - it is archive of VM, files of disks, and VM configs.
on import, VBox trying unpack ova before importing.
and cannot allocate memory for that.

**Comment by p1gmale0n** [comment]
on c4a67d5 
unpacking ova, importing _ovf_ instead _ova_

**Comment by asanaliev** [comment]
This issue is kind of intermittent (i.e. not consistent):
- I installed **manually** VirtualBox version 5.0.16, 5.0.18 and 5.0.20. Installed (3 times each) successfully with running vbox.
- When tested vbox installed (5.0.20) **by the Mac Installer**, got error once (out of 3).
- With the today updated installer I tested 5 times. The first one failed but other 4 installs completed successfully.
