### ISSUE TITLE
[UX Linux] Sub-menus are displayed separately from main menu 

### ISSUE THREAD

**Issue by ezununbekov** [subutai-io/installers#55]
![1](https://cloud.githubusercontent.com/assets/16970241/16175942/b6f76eee-3621-11e6-97ef-6bd49cd1ebd8.jpg)
 when choose any item of main menu - Launch or Environments or Virtual machines, main menu is disappeared and sub-menu seems to be an orphaned item. For example:

clicking Launch gives this
![22](https://cloud.githubusercontent.com/assets/16970241/16175965/77d031dc-3622-11e6-9772-05e87514e07e.jpg)

or Environments
![11](https://cloud.githubusercontent.com/assets/16970241/16175971/a48f4ffa-3622-11e6-92c7-ee26a978e466.jpg)

Looks unpretty

**Comment by btemir** [comment]
Win installer has no submenus (probably issue should be in tray)
