### ISSUE TITLE
[Win 7] Installation failed

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/installers#58]
I downloaded the latest version of Windows dev installer: Jun 21, 3 AM KGT. 

Got installation failed. I tried to install over WiFi, cable connected, or "run as admin" option. All of these attempts failed. 

![image](https://cloud.githubusercontent.com/assets/7465404/16214192/c328b0e0-3777-11e6-92b3-5563d3fe3259.png)

![image](https://cloud.githubusercontent.com/assets/7465404/16214216/eb7698f0-3777-11e6-8829-b8afe7b2e831.png)

![image](https://cloud.githubusercontent.com/assets/7465404/16214219/f0380b1c-3777-11e6-888a-c53335e1a0df.png)

Can't find any log files in `C:\Subutai\bin` dir. 

The following file contains created dirs structure:
[installed-dirs.txt](https://github.com/subutai-io/installers/files/324595/installed-dirs.txt)
# 

My Windows version:
![image](https://cloud.githubusercontent.com/assets/7465404/16214294/86103ba0-3778-11e6-9e11-07a563942428.png)

**Comment by asanaliev** [comment]
Comment from @btemir: 

> Logs are C:\temp\Subutai_Logs

**Comment by asanaliev** [comment]
[2016-06-21_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/324767/2016-06-21_Subutai_install_log.txt)

**Comment by asanaliev** [comment]
Tried just now and failed again. 

[2016-06-21_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/324798/2016-06-21_Subutai_install_log.txt)

![image](https://cloud.githubusercontent.com/assets/7465404/16218129/01c7e7c0-379c-11e6-8354-35ba7d748e78.png)

Chrome is downloaded although it is already installed. 
![image](https://cloud.githubusercontent.com/assets/7465404/16218144/2417e4f6-379c-11e6-802a-c3571b4ac40a.png)

VirtualBox is downloaded although it is already installed.
![image](https://cloud.githubusercontent.com/assets/7465404/16218160/420abe02-379c-11e6-8df2-064381aa04a6.png)

![image](https://cloud.githubusercontent.com/assets/7465404/16218168/566cf504-379c-11e6-8afb-03fcc854daaa.png)

**Comment by btemir** [comment]
Reproduced last case installing on machine with wired connection. Reason - could not find proper gateway interface.

**Comment by asanaliev** [comment]
Installed successfully the latest version.

**Comment by btemir** [comment]
Problem was in improper definition of default gateway. Changed to definig from netstat -r output rather than checking windows adapters
