### ISSUE TITLE
[Win 10] First installation failed

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/installers#59]
Failed to install on fresh Windows 10, i.e. I had not run the installer before on this system. Downloaded the latest installer from the site (didn't use the old version.)

The install was successful before the step "Waiting for SSH connection". Here, it spent ~10 min and failed after. 

Then I removed partially installed components and ran the installer again. This time the install completed successfully. 

[failed-2016-06-26_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/333891/failed-2016-06-26_Subutai_install_log.txt)
[success-2016-06-26_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/333892/success-2016-06-26_Subutai_install_log.txt)

**Comment by btemir** [comment]
@Next time please note virtual machine state in time of "Waiting for  SSH". If  in power off state, try to start manually to see what was wrong and why it did not start. If it hanged, try to restart it. In this case machine seems to be started but start could hang. I will throw exception if SSH waits more than 10 minutes (actually even if more than 5 it means something is wrong with virtual machine start or network settings.

**Comment by asanaliev** [comment]
I deleted existing Windows 10 and installed this OS again on same machine. And ran the Win installer. This time the installer completed successfully. 

Attached the install logs:
[2016-06-28_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/337765/2016-06-28_Subutai_install_log.txt)

**Comment by btemir** [comment]
Usually this situation arises when uninstall after unsuccessful installation. Adding auto uninstall if installation failes

**Comment by btemir** [comment]
reopened by mistake
