### ISSUE TITLE
[Win 10] Installation aborts itself

### ISSUE THREAD

**Issue by ezununbekov** [subutai-io/installers#63]
During installation some error occurs like in screenshot -

![1](https://cloud.githubusercontent.com/assets/16970241/16516315/3bfb09b8-3f99-11e6-8aed-fc816306c53f.JPG)

log here -
[2016-07-01_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/343101/2016-07-01_Subutai_install_log.txt)

**Comment by btemir** [comment]
Checked in Win logs, application crashed because of error in clr.dll (4.0=4.5 Framework), changed application settings.

**Comment by ezununbekov** [comment]
successfully installed on Win 10 RU
