### ISSUE TITLE
[Win] During installation Network Adapter not found or can not start

### ISSUE THREAD

**Issue by ezununbekov** [subutai-io/installers#66]
![1](https://cloud.githubusercontent.com/assets/16970241/16589437/f8f5ccfc-42f4-11e6-8820-d61830cb1436.JPG)
- this happens during installation. After this connection becomes limited so need to restart PC. Installation completes successfully though

Log
[2016-07-05_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/348039/2016-07-05_Subutai_install_log.txt)

**Comment by btemir** [comment]
Reproduced - adapter looses DNS settings after p2p or installer polling all network adapters. After some tries adapter starts and connection persists but any configuration of this (Wi-Fi) adapter is impossible. Started to work after adapter reinstallation. But in other case adapter stays unconfigurable.

**Comment by btemir** [comment]
For some cases (problems with adapter driver, preventing adapter to restart) it can be resolved by driver update or reinstall (remove adapter in device managed, install again with updated driver). In some cases it does not help at all and even if Subutai will be installed fro example without host-only adapter, problem will arise in p2p configuration.

**Comment by btemir** [comment]
Uninstall network adapter driver (network adapter connected to Internet) in Device manager and reboot Windows.
