### ISSUE TITLE
[Win] [Mac] Add daily log rotation to p2p.log

### ISSUE THREAD

**Issue by crioto** [subutai-io/installers#68]
Was reported by @akarasulu 

> Getting huge and tough to manage in one file. Let's do a daily log rotation.

Original issue is here: https://github.com/subutai-io/p2p/issues/169

**Comment by p1gmale0n** [comment]
done for mac
e9f4fadb69a8ee5c35e1bc7de1fe1c7be191bfe8

**Comment by btemir** [comment]
done for win, log will be rotated each time when p2p service restarts if size>5Mb.
