### ISSUE TITLE
[win] Can not ssh to container on windows of any version. Error messages "user mismatch".

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#69]
After installation can not to establish ssh connection to container. Can reach containers on other machine, fron tray on other machine can reach that container. 
Steps to reproduce:
1. Install VMWare Player on Ubuntu 16.04. Create virtual machine (please, allow VT-x for processor on creation, You can change it later, but it may not work in this case) with Windows (8, 10, 7 not checked yet). Check if E2E plugin installed, allow or install if not.
2.Stop Windows Firewall service (to ensure we have no firewall problem)
3. Install Subutai (with prod or dev installer downloaded from subut.ai). Launch SS, register peer
4. Create environment (with one container for this test, I've created with Mongo).
5. Go to Environment-Containers. Try to SSH
![image](https://cloud.githubusercontent.com/assets/16958983/16708556/3c0877f8-4609-11e6-9086-568bb1061c5f.png)
6. Try to ssh to this container from another machine, if You receive "Can not create directory "/home/<username>.ssh - Container is reachable. Or You can ping this container. 
7. Try to connect or ping container on another machine - it's reachable in my case. 
8. Try to SSH from SS again
![image](https://cloud.githubusercontent.com/assets/16958983/16708582/413306d4-460a-11e6-933a-5fbaff3d5d3f.png)
Got "Container is not ready" message.

![image](https://cloud.githubusercontent.com/assets/16958983/16708601/ff72213e-460a-11e6-9766-a4406778e6a0.png)

[karaflogs2016-07-09 18-25-36.txt](https://github.com/subutai-io/installers/files/355611/karaflogs2016-07-09.18-25-36.txt)
P2p for local and remote containers:
[p2p_log.txt](https://github.com/subutai-io/installers/files/355624/p2p_log.txt)
![image](https://cloud.githubusercontent.com/assets/16958983/16708694/65292c78-460d-11e6-9899-43b6d73a62fd.png)

[win_ipconfig.txt](https://github.com/subutai-io/installers/files/355631/win_ipconfig.txt)
[rh_ifconfig.txt](https://github.com/subutai-io/installers/files/355632/rh_ifconfig.txt)
[rh_p2p.txt](https://github.com/subutai-io/installers/files/355634/rh_p2p.txt)

**Comment by btemir** [comment]
Tried to connect from hub:
![image](https://cloud.githubusercontent.com/assets/16958983/16714907/1bdb9788-46e2-11e6-9870-aaf88b858ead.png)

**Comment by dilshat** [comment]
I tried the steps above on fresh version of p2p **p2p Cloud project 4.0.0-RC14-53-gf8556ff9. Packet version: 5**
First I could connect from inside Win10 via tray/ez-ssh to a container.
Then i tried to connect from outside (from host machine) - It didn't work.
After several minutes it started to ssh from host machine but stopped from Win10.
On Win10 i started getting `Connection timed out` in shell when doing ez-ssh

**Comment by dilshat** [comment]
Also when u run ifconfig on peer i see the following:
wan interface IP is 10.0.3.15
p2p100 interface IP is 10.92.143.1 (but SS does not assign such range to p2p!)
@tzununbekov @crioto

**Comment by dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/16723520/366c993e-476f-11e6-9172-eab645a5859f.png)

**Comment by dilshat** [comment]
[p2p.txt](https://github.com/subutai-io/installers/files/356682/p2p.txt)

**Comment by btemir** [comment]
log from physical machine, firewall turned off
[p2p.txt](https://github.com/subutai-io/installers/files/361434/p2p.txt)

**Comment by btemir** [comment]
tested on Win 8,10,7 (installed in that order)

On win 8 after installation and environment (2 containers) creation - could connect with ssh to both.
after ~2 hours it stopped to connect. Could not connect to remote containers after they were created on win10.
[rh_ifconfig.txt](https://github.com/subutai-io/installers/files/363553/rh_ifconfig.txt)
[host_ipconfig.txt](https://github.com/subutai-io/installers/files/363554/host_ipconfig.txt)
[p2p_log.txt](https://github.com/subutai-io/installers/files/363557/p2p_log.txt)

on RH:   ./p2p version
p2p Cloud project 4.0.0-RC14-72-gf0d7bf4. Packet version: 5
on host: 
C:>p2p version
p2p Cloud project 4.0.0-RC14-72-gf0d7bf4. Packet version: 5
![8_host_ping](https://cloud.githubusercontent.com/assets/16958983/16838091/3d0623a6-49e9-11e6-872f-f72d0916b98a.PNG)

On win10 after creation could connect to own containers, but not to remote. After ~1.5 hours started to connect to remote containers too. after ~1 hour more stopped to connect to own containers but still could connect to remote.
[p2p_log.txt](https://github.com/subutai-io/installers/files/363597/p2p_log.txt) 

On Win7 (installed 2 hours later) can connect to own and remote containers after 1 hour.
[p2p_log.txt](https://github.com/subutai-io/installers/files/363622/p2p_log.txt)

**Comment by btemir** [comment]
Just to fix the momentI: after creation: can connect to own containers, cannot to remote
~1 minutes passed: can connect to containers from remote machines
~2 minutes: can not connect to any containers
~4 minutes: can connect to own containers
~6 minutes: can connect to remote (time 0 = first try to connect from tray)

[p2p_show_debug.txt](https://github.com/subutai-io/installers/files/365390/p2p_show_debug.txt)
[p2p_log.txt](https://github.com/subutai-io/installers/files/365391/p2p_log.txt)
[host_ipconfig.txt](https://github.com/subutai-io/installers/files/365396/host_ipconfig.txt)
[rh_ifconfig.txt](https://github.com/subutai-io/installers/files/365400/rh_ifconfig.txt)

**Comment by dilshat** [comment]
is this still valid @btemir

**Comment by btemir** [comment]
After p2p win client update can ssh to local and remote containers.
