### ISSUE TITLE
Can not ssh into containers from Win

### ISSUE THREAD

**Issue by dilshat** [subutai-io/installers#70]
Steps to reproduce:
1) Create x-peer env with one peer on Win (7,8,10) and another on Linux
2) Try to ssh into containers from Linux - it works
3) Try to check env connectivity (telemetry) - it works
4) Try to ssh into containers from Win using ez-ssh or tray -  it fails with  "Container is not ready" or "Connection timed out" in opened shell.

Seems this problem is specific to Win p2p client.
P2P version tested: p2p Cloud project 4.0.0-RC14-56-g35f19b6. Packet version: 5 up to version 58

**Comment by dilshat** [comment]
Retested with P2P: 4.0.0-RC14-58-g6274c9e. Packet version: 5
Same problem - can not ssh into container from Win7
SSH terminal windows opened and failed with **Connection timed out** error

**Comment by crioto** [comment]
@Dilshat can you try to ping RH from host (win7) machine?

**Comment by dilshat** [comment]
After I restarted VM it started to work on Win7
Seems this happens on fresh installation or is related to CPs (instability)

**Comment by Dilshat** [comment]
@crioto RH is accessible from Win7 b/c I open SS UI by RH IP

**Comment by dilshat** [comment]
Seems this problem is reproduced on any Win version: 7, 8, 10
Reproduced on Win 8 and Win10 too

**Comment by dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/16798848/d6d5e2d0-490f-11e6-8a32-d6840900a059.png)

Still can not ssh from Win7 to containers
Also now can not ssh into Win7 container from outside
but can ssh into non Win7 containers from outside

Test were done on fresh VM with fresh peer

**Comment by dilshat** [comment]
[p2p.txt](https://github.com/subutai-io/installers/files/361163/p2p.txt)

**Comment by dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/16802885/c67d5534-4924-11e6-863c-a16fa5bb04e1.png)
Win 8

**Comment by dilshat** [comment]
The error reproduces on Win8, can not ssh into its containers. Can not ssh from it to remote containers

**Comment by absidish** [comment]
reproduced with win 10, physical machine, wired. firewall turned off.
[ipconfig_all.txt](https://github.com/subutai-io/installers/files/363625/ipconfig_all.txt)
[ifconfig_rh.txt](https://github.com/subutai-io/installers/files/363630/ifconfig_rh.txt)
[p2p_log.txt](https://github.com/subutai-io/installers/files/363631/p2p_log.txt)
[ping_rh.txt](https://github.com/subutai-io/installers/files/363632/ping_rh.txt)
![image](https://cloud.githubusercontent.com/assets/8696139/16838734/6dd9d2e0-49d3-11e6-8dac-eaf9628f5860.png)

**Comment by dilshat** [comment]
Reproduced on Win10 (p2p version 4.0.0-RC14-76-g2eddc70. Packet version: 5)

[p2p log on Win host](https://github.com/subutai-io/installers/files/363745/p2p.txt)

[ipconfig /all on Win host](https://github.com/subutai-io/installers/files/363753/ipconfig.txt)

[ifconfig on RH](https://github.com/subutai-io/installers/files/363755/ifconfig_rh.txt)

[p2p log on RH](https://github.com/subutai-io/installers/files/363765/p2p_log.txt)

**Comment by dilshat** [comment]
**p2p debug on RH:**

```
F9D7F36535BE1364371E1E4C7B54422483CC5DD8@/:>p2p debug
  DEBUG INFO:
Number of gouroutines: 19
Instances information:
Hash: swarm-64218059-41f4-4da3-a17d-afead4bcdd20
ID: ff3de526-49c0-11e6-8fd0-022d0fae0f03
Interface p2p100, HW Addr: 06:28:80:eb:c5:4c, IP: 10.82.232.2
Peers:
    --- fde60727-49c0-11e6-8873-022d0fae0f03 ---
        HWAddr: 06:7f:0f:11:bf:e1
        IP: 10.82.232.1
        Endpoint: 54.93.164.238:39823
        Peer Address: 158.181.130.115:48806
        Proxy ID: 36
    --- End of fde60727-49c0-11e6-8873-022d0fae0f03 ---
    --- 61165bad-49c1-11e6-805a-022d0fae0f03 ---
        HWAddr: 06:1f:8f:f5:9e:79
        IP: 10.82.232.245
        Endpoint: 54.93.222.10:50160
        Peer Address: 158.181.130.115:50598
        Proxy ID: 17
    --- End of 61165bad-49c1-11e6-805a-022d0fae0f03 ---
```

**P2p debug on Win host**

```
C:\Users\d>p2p debug
DEBUG INFO:
Number of gouroutines: 19
Instances information:
Hash: swarm-64218059-41f4-4da3-a17d-afead4bcdd20
ID: 743ee25c-49c1-11e6-865f-022d0fae0f03
Interface Local Area Network1, HW Addr: 00:ff:8:cd:91:8b, IP: 10.82.232.246
Peers:
        --- fde60727-49c0-11e6-8873-022d0fae0f03 ---
                HWAddr: 06:7f:0f:11:bf:e1
                IP: 10.82.232.1
                Endpoint: 54.93.222.10:50160
                Peer Address: 158.181.130.115:48806
                Proxy ID: 36
        --- End of fde60727-49c0-11e6-8873-022d0fae0f03 ---
        --- ff3de526-49c0-11e6-8fd0-022d0fae0f03 ---
                HWAddr: 06:28:80:eb:c5:4c
                IP: 10.82.232.2
                Endpoint: 192.168.56.101:48665
                Peer Address: 192.168.56.101:48665
                Proxy ID: 18
        --- End of ff3de526-49c0-11e6-8fd0-022d0fae0f03 ---
        --- 61165bad-49c1-11e6-805a-022d0fae0f03 ---
                HWAddr: 06:1f:8f:f5:9e:79
                IP: 10.82.232.245
                Endpoint: 54.93.222.10:50160
                Peer Address: 192.168.65.1:50598
                Proxy ID: 38
        --- End of 61165bad-49c1-11e6-805a-022d0fae0f03 ---
```

**p2p status on RH**

```
F9D7F36535BE1364371E1E4C7B54422483CC5DD8@/:>p2p status
  swarm-64218059-41f4-4da3-a17d-afead4bcdd20 | 10.82.232.2
743ee25c-49c1-11e6-865f-022d0fae0f03||State:Waiting forwarder IP|LastError:No forwarders received
fde60727-49c0-11e6-8873-022d0fae0f03|10.82.232.1|State:Connected|
```

**p2p status on Win host**

```
C:\Users\d>p2p status
swarm-64218059-41f4-4da3-a17d-afead4bcdd20 | 10.82.232.246
fde60727-49c0-11e6-8873-022d0fae0f03|10.82.232.1|State:Connected|LastError:Disconnected by timeout
61165bad-49c1-11e6-805a-022d0fae0f03|10.82.232.245|State:Handshaking|LastError:No forwarders received
ff3de526-49c0-11e6-8fd0-022d0fae0f03|10.82.232.2|State:Connected|LastError:Disconnected by timeout
```

**Comment by dilshat** [comment]
Peers are wireless to each other but in the same LAN, internet is wireless for both

env structure:

![image](https://cloud.githubusercontent.com/assets/3367326/16840814/7bf29374-49f8-11e6-869d-dee7d3c3bd2f.png)

ping, ssh and scp works inside env:

![image](https://cloud.githubusercontent.com/assets/3367326/16840718/fb8c7c68-49f7-11e6-8ef8-0f210697a9ee.png)

**Comment by dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/16841182/defd3562-498c-11e6-9f5a-c3b162fe5d17.png)

**Comment by dilshat** [comment]
On Win 8 and 10 ssh started working with Win client version **p2p Cloud project 4.0.0-RC14-79-g7e7ca7c. Packet version: 5**

However ping to remote containers/RH from Win host is unstable: ~ 25% -50% packet loss
So is connection - also unstable (slow) to remote containers

p2p in env passes tests (ssh,ping, scp)

**Comment by dilshat** [comment]
[ipconfig_all.txt](https://github.com/subutai-io/installers/files/365813/ipconfig_all.txt)

**Comment by dilshat** [comment]
```
C:\Subutai\bin>ping 10.29.92.2

Pinging 10.29.92.2 with 32 bytes of data:
Reply from 10.29.92.2: bytes=32 time=213ms TTL=64
Request timed out.
Reply from 10.29.92.2: bytes=32 time=283ms TTL=64
Request timed out.

Ping statistics for 10.29.92.2:
    Packets: Sent = 4, Received = 2, Lost = 2 (50% loss),
Approximate round trip times in milli-seconds:
    Minimum = 213ms, Maximum = 283ms, Average = 248ms

C:\Subutai\bin>
```

**Comment by dilshat** [comment]
```
C:\Users\Dilshat>p2p debug
DEBUG INFO:
Number of gouroutines: 19
Instances information:
Hash: swarm-acfcbca5-22b7-4723-8334-c3a63a1539b0
ID: dd4ece8d-4a7d-11e6-8e8d-022d0fae0f03
Interface Local Area Network1, HW Addr: 00:ff:12:57:98:1c, IP: 10.29.92.245
Peers:
        --- fd09d47c-4a7c-11e6-8a5e-022d0fae0f03 ---
                HWAddr: 06:65:02:7a:1d:8a
                IP: 10.29.92.246
                Endpoint: 192.168.65.1:36995
                Peer Address: 192.168.65.1:36995
                Proxy ID: 0
        --- End of fd09d47c-4a7c-11e6-8a5e-022d0fae0f03 ---
        --- 0568c747-4a7d-11e6-8400-022d0fae0f03 ---
                HWAddr: 06:cf:45:fa:a7:2b
                IP: 10.29.92.1
                Endpoint: 192.168.56.101:46644
                Peer Address: 192.168.56.101:46644
                Proxy ID: 0
        --- End of 0568c747-4a7d-11e6-8400-022d0fae0f03 ---
        --- fcf4fd1e-4a7c-11e6-8896-022d0fae0f03 ---
                HWAddr: 06:4b:50:4d:37:15
                IP: 10.29.92.2
                Endpoint: 54.93.164.238:39823
                Peer Address: 158.181.134.116:43851
                Proxy ID: 69
        --- End of fcf4fd1e-4a7c-11e6-8896-022d0fae0f03 ---
```

```

C:\Users\Dilshat>p2p status
swarm-acfcbca5-22b7-4723-8334-c3a63a1539b0 | 10.29.92.245
fd09d47c-4a7c-11e6-8a5e-022d0fae0f03|10.29.92.246|State:Connected|
0568c747-4a7d-11e6-8400-022d0fae0f03|10.29.92.1|State:Connected|
fcf4fd1e-4a7c-11e6-8896-022d0fae0f03|10.29.92.2|State:Connected|

```

**Comment by crioto** [comment]
@Dilshat is your connection wireless?

**Comment by crioto** [comment]
@Dilshat also, does it reproduces every time?

**Comment by dilshat** [comment]
@crioto connection is wireless. 
On Win 10 ping stabilized after p2p service restart and some time passed but on Win8 it didnt

Right after Win peer setup and env creation it reproduces for me every time

**Comment by btemir** [comment]
Can not connect to container on x-peer after ~5 hours after creation. Created x-peer environment with 2 containers on win peers (one on phys. win8.1 - wireless, another on win-VMware-win10 - wired). After creation could connect with ssh to both environments from third machine (phys. win8.1). After ~5 hours: can connect with ssh to one container (running on vm /wired connection) and can not connect to another (running on machine with wireless, IP 10.120.104.2).
p2p debug:
**C:\Subutai\bin>p2p debug
DEBUG INFO:
Number of gouroutines: 20
Instances information:
Hash: swarm-bec602e0-1d68-46e1-961a-72d5eb045af3
ID: f92122cb-4d17-11e6-8348-022d0fae0f03
Interface Local Area Network1, HW Addr: 00:ff:01:8c:1a:e7, IP: 10.120.104.245
Peers:
        --- eb526d62-4d17-11e6-82b8-022d0fae0f03 ---
                HWAddr: 06:d3:95:bb:36:f3
                IP: 10.120.104.1
                Endpoint: 54.93.222.10:49218
                Peer Address: 195.114.241.233:60348
                Proxy ID: 11
        --- End of eb526d62-4d17-11e6-82b8-022d0fae0f03 ---
        --- eb351270-4d17-11e6-88ce-022d0fae0f03 ---
                HWAddr: 00:ff:38:5a:6f:00
                IP: 10.120.104.245
                Endpoint: 54.93.222.10:49218
                Peer Address: 195.114.241.233:65496
                Proxy ID: 10
        --- End of eb351270-4d17-11e6-88ce-022d0fae0f03 ---
        --- f057b772-4d17-11e6-88ff-022d0fae0f03 ---
                HWAddr: 00:ff:2f:aa:51:57
                IP: 10.120.104.246
                Endpoint: 54.93.164.238:53963
                Peer Address: 212.42.107.149:56294
                Proxy ID: 18
        --- End of f057b772-4d17-11e6-88ff-022d0fae0f03 ---
C:\Subutai\bin>**
p2p log: 
[p2p_log.txt](https://github.com/subutai-io/installers/files/369897/p2p_log.txt)

after some tries SubutaiTray crashed, restarted tray and p2p service. after ~ 6 minutes connected to the second container

**Comment by btemir** [comment]
Long running test: stop to connect to env with ssh after some time (~1 hour after p2p service restart, need to test more to find), need to restart p2p service to connect again (before had experience with 7 days running environment on the same machine without problems)

[p2p_log.txt](https://github.com/subutai-io/installers/files/410519/p2p_log.txt)
![image](https://cloud.githubusercontent.com/assets/16958983/17545714/66574cd8-5eef-11e6-8b2d-6503815e9f3d.png)
