### ISSUE TITLE
Test installation with VBox releases 5.0.26 and 5.1

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#72]
Had problems with VBox releases 5.0.22 and 5.0.24 on installation - VM not showed in VBox Manager and stuck after installation completed.  Need to check if the reason is in new releases features or not fully uninstalled previously installed VBox instances.

**Comment by btemir** [comment]
5.0.26 seems to be OK.

**Comment by btemir** [comment]
5.0.26: installation steps related to VM run, but no machine in VBoxManager GUI on Win7, VirtualBox installed before. Could fix just with installing 5.0.20.

**Comment by btemir** [comment]
Uninstallation of Vbox 5.0.26 seems to be a problem. After removing of VirtualBox (it can look as unsuccessful uninstall) need to restart machine - VirtualBox uninstalled.

**Comment by btemir** [comment]
Testing 5.1.2: vbox installed successfully, but on reinstall preinstall form shows "installation impossible" for this version. Fixing

**Comment by btemir** [comment]
5.1.2 on Win 8.1. Does not show VM or shows with wrong state. HostOnly adapter does not work. need to research

**Comment by p1gmale0n** [comment]
tested 5.0.26 and 5.1.2 on mac
no issues found

**Comment by p1gmale0n** [comment]
tested on 5.1.4 mac
no issues found

**Comment by btemir** [comment]
![vm_noidea](https://cloud.githubusercontent.com/assets/16958983/17773314/a11733de-656f-11e6-9206-81f806f7a6c4.PNG)

**Comment by btemir** [comment]
Tested 5.1.4 - the same problem.

**Comment by p1gmale0n** [comment]
tested on 5.1.6 mac
no issues found
