### ISSUE TITLE
Different balances on Hub and on the Windows Installer

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/installers#77]
![screenshot_20160804191620](https://cloud.githubusercontent.com/assets/17665678/17403119/2544f87e-5a78-11e6-82f5-e28eb8b11c0b.png)

**Comment by btemir** [comment]
Windows Installer has no balance.

**Comment by akylbekesenaliev** [comment]
@btemir thats right,my bad, got confused a bit ...
