### ISSUE TITLE
[Win] RH IP address can not be defined after import management or later

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#95]
`sudo subutai management_network` or `sudo subutai info ipaddr`command returns null:
it can happen at installation time or later
if happens at installation time - installation fails 
but it can happen later, so we need to find a reason

**Comment by akylbekesenaliev** [comment]
GUI Network 
Adapter #1 
![image](https://cloud.githubusercontent.com/assets/17665678/19142144/15fb220a-8bbd-11e6-9868-22b85e6c92e9.png)
Adapter #2 
![image](https://cloud.githubusercontent.com/assets/17665678/19142154/25670696-8bbd-11e6-965b-71c3da166bbb.png)
Adapter #3 
![image](https://cloud.githubusercontent.com/assets/17665678/19142160/331f3448-8bbd-11e6-914c-631ae3bb5aa3.png)
Ifconfig : 
Part #1 
![image](https://cloud.githubusercontent.com/assets/17665678/19142169/514c9af0-8bbd-11e6-86b2-6eafe8dfe5b9.png)
Part#2
![image](https://cloud.githubusercontent.com/assets/17665678/19142183/6af3f70a-8bbd-11e6-8439-8c55c44ebd3c.png)
sudo subutai management_network detect command output : 
![image](https://cloud.githubusercontent.com/assets/17665678/19142211/9f36aef4-8bbd-11e6-83e4-d3f5e48d48c5.png)

**Comment by akylbekesenaliev** [comment]
Windows/CMD - ipconfig/all  : 
Part #1 
![image](https://cloud.githubusercontent.com/assets/17665678/19142294/30bbedc6-8bbe-11e6-8afe-c551ad0ba9cb.png)
Part #2 
![image](https://cloud.githubusercontent.com/assets/17665678/19142304/43c1373c-8bbe-11e6-9b79-12614c8e0187.png)
Part #3 
![image](https://cloud.githubusercontent.com/assets/17665678/19142311/5270cee6-8bbe-11e6-924a-f290d649ffc1.png)
Part #4 
![image](https://cloud.githubusercontent.com/assets/17665678/19142319/636fb388-8bbe-11e6-9d9f-351fe97118fc.png)

**Comment by btemir** [comment]
one of the reasons - second default route
it should be deleted with command under Admin account
`route delete 0.0.0.0 mask 0.0.0.0 <x.x.x.x>
`

**Comment by btemir** [comment]
eth2 (host-only interface) has no IPv4 address. This is caused by wrong DHCP server configuaration on machines with this problem: it has all 0.0.0.0. DHCP server is created for new Host-Only interface by default (?), and it prevents proper configuration `with vboxmanege dhcp add`. So we need to remove existing DHCP server  befor configure new with our settings.
Done
On machine with problem:

```
ifconfig eth
eth2      Link encap:Ethernet  HWaddr 08:00:27:2f:ca:cd
         inet addr:192.168.56.100  Bcast:192.168.56.255  Mask:255.255.255.0
         inet6 addr: fe80::a00:27ff:fe2f:cacd/64 Scope:Link
         UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
         RX packets:942 errors:0 dropped:0 overruns:0 frame:0
         TX packets:156 errors:0 dropped:0 overruns:0 carrier:0
         collisions:0 txqueuelen:1000
         RX bytes:221559 (221.5 KB)  TX bytes:48542 (48.5 KB)

```

**Comment by btemir** [comment]
In process of testing
